import Head from 'next/head';
import Image from 'next/image';
import matter from 'gray-matter';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

type Content = {
    title: string
}

export default function Home() {
	const [data, setData] = useState<Content>();

	async function getHeader() {
		const content = await import(`../content/home.md`);
		const data = matter<string, {}>(content.default);
		setData(data.data as Content);
	}

	useEffect(() => {
		getHeader();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main className={styles.main}>
				<div>{data ? data.title : 'Loading'}</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
